### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by Ithamar** [crowdedjs/recast-detour#1]
Is this repo still maintained? While testing navmesh generation with complex scenes, I've found a bunch of bugs, which look like they are simply oversights when converting the Java code to JS. I can continue figuring them out and posting MRs for them here, if it is likely they'll be included.

Also, I would like a little more of the Recast/Detour APIs to be exported, would that be accepted?

Really nice work on the conversion, would love to use this!

**Comment by bricksphd** [comment]
Hi @Ithamar. This is still actively maintained. Any bugs that you find would be really appreciated, along with expanding the API.

**Comment by Ithamar** [comment]
Okay, it might take a couple of days to cook up proper MRs for both, but I should have something by the weekend.
